
//@version=4
study("Exponential Moving Averages", overlay=true)


length1 = input(7, minval=1)
length2 = input(21, minval=1)
length3 = input(99, minval=1)


ema1_value = ema(close, length1)
ema2_value = ema(close, length2)
ema3_value = ema(close, length3)


plot(ema1_value, color= color.orange, linewidth=2,  title="EMA 7-day")
plot(ema2_value, color=color.green, linewidth=2,  title="EMA 21-day")
plot(ema3_value, color=color.blue, linewidth=2,  title="EMA 99-day")
